name: Deploy CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: install deps and build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        cd src/github.com/${{ github.repository }}
        make deps
        make ensure
        make test
        make build-linux-amd64

    - name: Login to Quay.io
      uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: test build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          quay.io/elisaoyj/kops-autoscaler-openstack:latest
          quay.io/elisaoyj/kops-autoscaler-openstack:${{ github.sha }}
