name: PR test CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: install deps and build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        cd src/github.com/${{ github.repository }}
        make deps
        make ensure
        make test
        make build-linux-amd64

    - name: test build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: foobar:latest
